name: readme2tex-action
author: montali
description: GH action that automatically builds every .tex.md file in the repo
branding:
  icon: "dollar-sign"
  color: "green"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

inputs:
  user_name:
    description: 'The name of the user who will commit'
    required: true
  user_email:
    description: 'The e-mail address of the user'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install pdflatex and rename
      run: sudo apt-get install texlive-latex-base rename
      shell: bash
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install readme2tex
        python3 -V
        python3 -m pip -V
      shell: bash
    - name: Build readmes
      id: build-readmes
      run: find . -type f -name '*.tex.md' -execdir python3 -m readme2tex --readme {} --nocdn --output "{}" \;
      shell: bash
    - name: Rename built .md files
      run: find . -type f -name '*.tex.md' -exec rename 's/.tex.md/.md/' '{}' \;
      shell: bash
    - name: Commit the built files
      run: |
        git config --global user.name '${{ inputs.user_name }}'
        git config --global user.email '${{ inputs.user_email }}'
        git diff --quiet || (git add . && git commit -m "Built the .tex.md files")
        git push
      shell: bash